// MFCApplication1.idl : MFCApplication1 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(MFCApplication1.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(96D7D966-DA60-4189-81B4-2A170A253073),
	version(1.0)	
]
library MFCApplication1Lib
{
	importlib("stdole2.tlb");
};
